export const SET_ITEMS_REQUEST = 'SET_ITEMS_REQUEST';
export const SET_ITEMS_SUCCESS = 'SET_ITEMS_SUCCESS';
export const SET_ITEMS_FAILURE = 'SET_ITEMS_FAILURE';
export const SET_ITEM_REQUEST = 'SET_ITEMS_REQUEST';
export const SET_ITEM_SUCCESS = 'SET_ITEMS_SUCCESS';
export const SET_ITEM_FAILURE = 'SET_ITEMS_FAILURE';