export const SET_PROFILE_REQUEST = "SET_PROFILE_REQUEST";
export const SET_PROFILE_SUCESS = "SET_PROFILE_SUCCESS";
export const SET_PROFILE_FAILURE = "SET_PROFILE_FAILURE";
export const SET_USER_REQUEST = "SET_USER_REQUEST";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAILURE = "SET_USER_FAILURE";
export const ADD_ITEM = "ADD_ITEM";


